services:
  assets-server:
    image: "httpd:2.4-alpine"
    volumes:
      - "./web_assets/:/usr/local/apache2/htdocs/"
    ports:
      - "8080:80"
    develop:
      watch:
        - action: sync
          path: ./web_assets
          target: /usr/local/apache2/htdocs

  web-ui:
    build: .
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json
